services:
  - type: web
    name: emissor-nfe-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: mysql://usuario:senha@host:3306/emissor_nfe_2025
    rootDir: backend

  - type: web
    name: emissor-nfe-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: frontend
